Repository go-sql-driver/mysql, pull requests merged in 2018-05, with the labels that each got.

#794 Support caching sha2 password
  AUTHORS
  const.go
  driver.go
  driver_test.go
  packets.go
  utils.go
  utils_test.go
Labels: bug, enhancement

#798 Travis: Add MySQL 8.0 test enviornment
  .travis.yml
  .travis/wait_mysql.sh
Labels: testing

#801 Fix 'panic: runtime error: slice bounds out of range'
  AUTHORS
  packets.go
Labels: bug

#802 packets: add regression test for #801
  packets_test.go
Labels: testing

#800 Fix empty SHA2 password handling
  const.go
  driver.go
  driver_test.go
  packets.go
Labels: bug

#811 Skip flaky cancellation test checks that depend on a race-condition
  driver_go18_test.go
Labels: testing
