Repository go-sql-driver/mysql, pull requests merged in 2018-06, with the labels that each got.

#808 sha256_password auth support
  README.md
  auth.go
  auth_test.go
  dsn.go
  dsn_test.go
  packets.go
  utils.go
Labels: enhancement

#809 Release v1.4.0
  CHANGELOG.md
Labels: organization

#818 Fix TIME format for binary columns
  packets.go
  utils.go
  utils_test.go
Labels: bug
