Repository go-sql-driver/mysql, pull requests merged in 2019-09, with the labels that each got.

#995 Refactor NullTime as go1.13's sql.NullTime
  nulltime.go
  nulltime_go113.go
  nulltime_legacy.go
  nulltime_test.go
  utils.go
  utils_test.go
Labels: Go1.13

#997 conncheck: move var declarations into closure
  conncheck.go
  conncheck_dummy.go
Labels: performance

#1000 move CONTRIBUTING.md to .github/CONTRIBUTING.md
  .github/CONTRIBUTING.md
Labels: documentation
