Repository go-sql-driver/mysql, pull requests merged in 2020-05, with the labels that each got.

#1092 Travis allow Go master to fail
  .travis.yml
Labels: testing

#1090 mysqlStmt Implements CheckNamedValue
  AUTHORS
  statement.go
Labels: enhancement

#1098 performance improvement for parseDateTime
  AUTHORS
  utils.go
  utils_test.go
Labels: performance

#1099 On connect, set all variables in a single SET statement
  connection.go
Labels: performance

#1097 Added fuzzer
  fuzz.go
Labels: testing

#1104 travis: do not run compile check in matrix builds
  .travis.yml
  .travis/compile_check.sh
Labels: testing

#1103 travis: update image versions
  .travis.yml
  .travis/wait_mysql.sh
Labels: testing

#1113 utils: parse using byteslice in parseDateTime
  AUTHORS
  nulltime.go
  packets.go
  utils.go
  utils_test.go
Labels: performance
